services:
  conspectus:
    image: conspectus
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      dockerignore: ./docker/.dockerignore
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
