services:
  conspectus:
    image: conspectus
    build:
      args:
        - NODE_ENV=development
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../build:/usr/src/app/build
      - ../public:/usr/src/app/public
      - ../src:/usr/src/app/src
      - ../types:/usr/src/app/types
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
