name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: ls -l config/
      - run: cat config/.prettierrc.js
      - run: cat config/.prettierignore
      - run: pnpm prettier --version
      - run: pnpm eslint --version      
      - run: pnpm lint
